repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict    # Check for files that contain merge conflict strings
      - id: trailing-whitespace     # This hook trims trailing whitespace
      - id: end-of-file-fixer       # Ensures that a file is either empty, or ends with one newline
      - id: detect-private-key      # Detects the presence of private keys
      - id: check-json              # This hook checks json files for parseable syntax
      - id: check-yaml              # This hook checks yaml files for parseable syntax
      - id: detect-aws-credentials  # Detects *your* aws credentials from the aws cli credentials file
        args:
          - --allow-missing-credentials

  # please refer to: https://github.com/antonbabenko/pre-commit-terraform#available-hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tfsec
      - id: terraform_docs

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terragrunt-hclfmt
